// Client runtime: router outlet and link custom elements.
import '@beatzball/litro/runtime/LitroOutlet.js';
import '@beatzball/litro/runtime/LitroLink.js';

// Custom elements
import './components/file-preview.js';
import './components/project-tree.js';
import './components/shutdown-dialog.js';
import './components/session-row.js';
import './components/chat-tool-call.js';
import './components/chat-message.js';
import './components/chat-input.js';
import './components/chat-panel.js';

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

document.addEventListener('DOMContentLoaded', () => {
  const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
  if (outlet) {
    outlet.routes = routes;
  } else {
    console.warn('[litro] <litro-outlet> not found — router will not start.');
  }
});
