// CRITICAL: must be first — patches LitElement before any component is loaded.
import '@lit-labs/ssr-client/lit-element-hydrate-support.js';

// Client runtime: router outlet and link custom elements.
import '@beatzball/litro/runtime/LitroOutlet.js';
import '@beatzball/litro/runtime/LitroLink.js';

// Routes generated by the page scanner before each vite build.
import { routes } from './routes.generated.js';

document.addEventListener('DOMContentLoaded', () => {
  const outlet = document.querySelector('litro-outlet') as (Element & { routes: unknown }) | null;
  if (outlet) {
    outlet.routes = routes;
  } else {
    console.warn('[litro] <litro-outlet> not found — router will not start.');
  }
});
