// @ts-nocheck
// @generated by litro page scanner — do not edit
// This file is consumed by the Litro client bootstrap (app.ts).
// Re-generated on every build.

import type { Route } from '@beatzball/litro/runtime';

export const routes: Route[] = [
  {
    path: "/",
    action: async () => { await import("./pages/index.js"); },
    component: "page-home",
  },
  {
    path: "/models",
    action: async () => { await import("./pages/models.js"); },
    component: "page-models",
  },
  {
    path: "/workspace",
    action: async () => { await import("./pages/workspace.js"); },
    component: "page-workspace",
  },
];
